Repository chingu-voyages/v9-bears-team-30, pull requests merged in 2019-06, with the labels that each got.

#26 Combined user-related APIs in one file
  server.js
  server/routes/signupApi.js
  server/routes/userApi.js
  src/actions/putSignupAction.js
Labels: refactor

#31 Added url-loader to webpack to load local images
  package-lock.json
  package.json
  src/components/routes/signup.css
  webpack.config.js
Labels: bug

#32 Added json world map with global temperature data
  package-lock.json
  package.json
  public/worldmap.json
  src/components/WorldMap.js
  src/components/routes/Home.js
  src/components/routes/Users.js
  src/components/worldmap.css
Labels: ToDo

#37 Feature/navbar
  src/components/Header.js
  src/components/app.css
  src/components/header/Header.js
  src/components/header/header.css
  src/components/layouts/layout.js
  src/components/routes/Home.js
  src/components/sidedrawer/DrawerToggleButton.js
  src/components/sidedrawer/SideDrawer.js
  src/components/sidedrawer/sideDrawer.css
  src/components/worldmap/WorldMap.js
  src/components/worldmap/worldmap.css
Labels: ToDo

#39 Feature/name seo - Browser Tab Display
  package-lock.json
  public/index.html
Labels: chore

#44 Updated project name, description and authors
  package.json
Labels: chore

#46 adds header to signup and signin pages
  src/components/header/header.css
  src/components/routes/SignInPage.js
  src/components/routes/SignUpPage.js
  src/components/routes/signup.css
  src/components/sidedrawer/sideDrawer.css
Labels: ToDo, bug

#51 Added link to signin page to navbar
  src/components/header/Header.js
Labels: chore

#52 Feature/weathersearch
  package-lock.json
  package.json
  src/components/routes/index.js
  src/components/routes/search/CityData.js
  src/components/routes/search/citydata.css
  src/components/weathersearch/DataViz.js
  src/components/weathersearch/DataViz2.js
  src/components/weathersearch/USWeatherSearch.js
  src/components/weathersearch/dataviz.css
  src/components/weathersearch/weathersearch.css
  src/components/worldmap/WorldMap.js
  src/components/worldmap/worldmap.css
  webpack.config.js
Labels: enhancement

#55 Refactor/sidedrawer
  README.md
  src/components/header/Header.js
  src/components/header/header.css
  src/components/routes/search/CityData.js
  src/components/routes/search/citydata.css
  src/components/routes/worldsearch/CountryData.js
  src/components/sidedrawer/DrawerToggleButton.js
  src/components/sidedrawer/SideDrawer.js
  src/components/sidedrawer/sideDrawer.css
  src/components/weathersearch/USWeatherSearch.js
  src/components/weathersearch/WorldWeatherSearch.js
  src/components/weathersearch/dataviz.css
  src/components/weathersearch/weathersearch.css
  src/components/worldmap/WorldMap.js
Labels: bug, chore

#56 Feature/add auth with passport
  package-lock.json
  package.json
  server.js
  server/config/keys.js
  server/config/passport.js
  server/routes/userApi.js
  src/actions/getSigninAction.js
  src/components/PrivateRoute.js
  src/components/routes/Dashboard.js
  src/components/routes/SignInPage.js
  src/components/routes/index.js
  src/reducers/getSigninReducer.js
  src/utils/setAuthToken.js
Labels: enhancement

#61 Changed hard-coded token to environment variable
  src/components/routes/search/CityData.js
Labels: security
